apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
  namespace: config-management-system
spec:
  clusterName: exam
  git:
    syncRepo: git@github.com:volenin/csp-config-management.git
    syncBranch: "master"
    secretType: ssh
    policyDir: "hello-namespace/config-root"
